### ISSUE TITLE
filesystem hook ran before encryptssh was done

### ISSUE THREAD

**Issue by Loader009** [grazzolini/mkinitcpio-utils#12]
Hey there,
I updated last summer an ARM device but sadly it stopped working after a reboot.
Now I took the time to investigate and I reinstalled it from scratch.

Sadly the same error appeared, so I am out of ideas.
After the device [details will be down there] has partially booted I end up in an emergency shell in the initrd.
Please take a look at the picture.
If I try to ssh, I get the same error-message as by running cryptsetup_shell.

Can you tell me how to check what is wrong?

I can boot into a secondary system and arch-chroot into the encrypted system easily to debug if needed.
Board: Odroid XU4 with a Samsung Exynos CPU (ARM); headless setup but with HDMI to TV for debugging.
Booting from mSD, then from there to USB-SSD (all mSD is unreliable for me because of silent data corruption)
![stopping at initramfs](https://user-images.githubusercontent.com/9888311/34957595-2509028e-fa26-11e7-84a1-e36c025afa77.jpg)

**Comment by Loader009** [comment]
I think this has something to do with this:
https://github.com/grazzolini/mkinitcpio-utils/commit/d7ae7252254df4552405ce96bb590d3b2fc41132

Now I know a workaround but this should be debugged and fixed properly I think.
Let me know what else information you need and what I can do to support you at debugging.

**Comment by ShapeShifter499** [comment]
I'm seeing this same issue on a Raspberry Pi 3B+ running a aarch64 kernel in Arch Linux Arm.

I see more or less the same output as the above image, it drops to a emergency shell.   Trying to ssh at this state gives me the following error. 

```
[raansu@Y40-80 ~]$ ssh root@192.168.1.15 -i .ssh/pi-tests/pi3-testkey-rsa
encryption bootup not succeeded. please wait!
Connection to 192.168.1.15 closed.
```

**Comment by ShapeShifter499** [comment]
@grazzolini  Any updates on this?

@Loader009 what's the workaround that you know of?

**Comment by ShapeShifter499** [comment]
@Loader009 What are you using instead?

**Comment by grazzolini** [comment]
It looks from the error, not that filesystem is being ran before it, but that the rootfs is not being properly resolved. I have changed to hook to use that, because it's the appropriate function to find the resolved name for the device and also because the encrypt hook does that. Perhaps, arm has some issue here. Can you try to increase the rootdelay parameter from the default (10 seconds) to something else? Also, make sure you're using one of the unique identifiers available: UUID, PARTUUID, LABEL and PARTLABEL.

**Comment by ShapeShifter499** [comment]
I had  in my cmdline     cryptdevice=/dev/disk/by-uuid/UUID:root

**Comment by ShapeShifter499** [comment]
@grazzolini I had 'rootwait'       Isn't that better or worse than rootdelay?

**Comment by grazzolini** [comment]
@ShapeShifter499, I don't think initcpio understands rootwait. The only parameter I know about is rootdelay. Using the /dev path should work, but that's conditional on having udev working. Try using the UUID= format instead. I had some issues with my ssd disk, and I had to explicitly use the /dev/nvme path for it, so, not everything works by UUID or /dev/disk/by-* paths. Make sure you try using all of the options, so we can discard an issue with mkinitcpio-utils.

**Comment by ShapeShifter499** [comment]
ok so in my kernel command line I'm swapping rootwait for rootdelay=10     and then I'm changing the cryptdevice line to look like "cryptdevice=UUID=(ID)"

**Comment by grazzolini** [comment]
@ShapeShifter499 rootdelay already defaults to 10. You can always remove it. It should only be necessary if your device initialization takes a very long time.

**Comment by ShapeShifter499** [comment]
@grazzolini These are my settings right now (with the UUID edited out).  Attached is a photo of the terminal output from my Raspberry Pi

```
mkinitcpio.conf
HOOKS=(base udev autodetect modconf block netconf dropbear encryptssh filesystems keyboard fsck)
```
```
/boot/cmdline.txt
cryptdevice=/dev/disk/by-uuid/(UUID-id):root root=/dev/mapper/root rootdelay=20 console=ttyAMA0,115200 console=tty1 selinux=0 plymouth.enable=0 smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 kgdboc=ttyAMA0,115200 elevator=noop ip=:::::eth0:dhcp
```

![img_20180508_144451571](https://user-images.githubusercontent.com/388665/39784840-c270b020-52ce-11e8-810c-e96497a3063e.jpg)

**Comment by ShapeShifter499** [comment]
@grazzolini It's not even asking for my Passphrase so I don't know why it's waiting for '/dev/mapper/root'   It isn't even decrypted and mounted at that point.

**Comment by grazzolini** [comment]
It's weird, because the encryptssh hook is not even prompting for a password, when it should be. Can you pass the break=premount option and try to source the init_functions file and check what's the output of the resolve_device() function? Sometimes debugging from the initramfs is the only way.

**Comment by ShapeShifter499** [comment]
Here is the snip, it appears to fit all on the TV display.  Attached is the clearest photo I could get.
![img_20180508_152303722](https://user-images.githubusercontent.com/388665/39786191-3a2efacc-52d4-11e8-9221-97bd0c657c3a.jpg)

**Comment by ShapeShifter499** [comment]
@grazzolini "source the init_functions file and check what's the output of the resolve_device() " 
sorry I might have misunderstood what you wanted me to do

**Comment by grazzolini** [comment]
What I meant is that you should run:

`source init_functions`

And then run the resolve_device function from within the break=premount shell. The same way the encryptssh hook calls it.

**Comment by ShapeShifter499** [comment]
@grazzolini  Going from the source code https://github.com/grazzolini/mkinitcpio-utils/blob/e2d1dedc7be0ad0038ba4e73fe2200921ac5d49c/initcpio/hooks/encryptssh#L73     
I ran the following
```
source init_functions resolve_device UUID=(ID) 10
```
I got no output

**Comment by grazzolini** [comment]
@ShapeShifter499 

Ok, so lets go step by step. First, pass break=premount to the kernel cmdline so you're dropped to the root shell. Then run:

`source /init_functions`
`resolve_device UUID=<the device uuid>`

It should return to you the /dev/sdX or /dev/nvmeX path of the actual device.

**Comment by ShapeShifter499** [comment]
I know my encrypted partition is LUKS and it should be at /dev/mmcblk0p2   (the second partition of my SD)      But those commands above return nothing with the UUID of the LUKS partition.

**Comment by grazzolini** [comment]
@ShapeShifter499 
It looks like resolve_device is having problems resolving your device. This is probably a bug within either systemd-udev (it is the udev used on the initramfs) or mkinitcpio itself. This is why the encryptssh hook is not prompting for a password. I don't have an arm hardware with sd to test this, but if you can debug this further and report, it would be great.

**Comment by ShapeShifter499** [comment]
@grazzolini ok I was able to play around with it.   I got some output this time. Maybe I typed some stuff wrong, I'm sorry.

```
sh: bad number
/dev/mmcblk0p2
```

**Comment by ShapeShifter499** [comment]
same error above if I invoke the 'ash' shell
```
ash: bad number
/dev/mmcblk0p2
```

**Comment by ShapeShifter499** [comment]
@grazzolini after some assistance from ##linux channel on Freenode.    I've narrowed down the issue to this line in my init_functions file.
```
[ -z "$dev" -a "$udevd_running" -eq 1 ] 
```   
which becomes      
```
 [ -z /dev/mmcblk0p2 -a -eq 1 ]
```
which is throwing the "ash: bad number" error

**Comment by grazzolini** [comment]
@ShapeShifter499 

You might be onto something. I'm going to try to debug this. I had a similar issue with my nvme device and I also get that bad number there. I'm going to check with Dave Reisner, the mkinitcpio developer.

**Comment by ShapeShifter499** [comment]
I no longer have any issues with this package.

**Comment by Loader009** [comment]
@ShapeShifter499 atm I don't use my arm device (should change in the next few weeks) and I am also testing another distribution, so I don't know if I will use this package in the future.
But thank you for mentioning that, I will probably test another kernel and report it if it's an issue.
